In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


## Import

In [2]:
import pandas as pd
import random
import os
import numpy as np

from sklearn.linear_model import LinearRegression
from sklearn.multioutput import MultiOutputRegressor

In [3]:
def seed_everything(seed):
    random.seed(seed)
    os.environ['PYTHONHASHSEED'] = str(seed)
    np.random.seed(seed)
seed_everything(42) # Seed 고정

## Data Load

In [4]:
train_x = pd.read_csv('/content/drive/MyDrive/데이콘/[데이콘]LG/data/train.csv').drop(columns=['ID'])
test_x = pd.read_csv('/content/drive/MyDrive/데이콘/[데이콘]LG/data/test.csv').drop(columns=['ID'])

## smote를 위해 임의로 큰 값을 생성

In [8]:
data_temp = []
for i in range(70):
  data_temp.append(999999.0)

In [9]:
from imblearn.over_sampling import SMOTE
import math

data_temp_np = np.array(data_temp * math.ceil(len(train_x) * 1.25)).reshape(-1,70)
increase_data = pd.DataFrame(data_temp_np, columns = train_x.columns)
train_x["class"] = 0 # 기존 데이터 label 0
increase_data["class"] = 1 # 임의 데이터 lable 1
new_train_x = pd.concat([train_x,increase_data],axis=0) # 임의 생성 데이터 concat

sm = SMOTE(random_state=42)
X_res, y_res = sm.fit_resample(new_train_x.iloc[:,:-1], new_train_x["class"])

# Smote
- 분류문제가 아니기에 임의로 기존 데이터(0), 임의 데이터(1)로 하여 기존 데이터를 1.25배 증량 > 성능 향상



In [10]:
from imblearn.over_sampling import SMOTE

sm = SMOTE(random_state=42)
X_res, y_res = sm.fit_resample(new_train_x.iloc[:,:-1], new_train_x["class"])

In [11]:
temp_df = pd.concat([X_res,y_res],axis=1)

In [12]:
train_df =temp_df[temp_df["class"] == 0].iloc[:,:-1]

In [13]:
train_x = train_df.filter(regex='X') # Input : X Featrue
train_y = train_df.filter(regex='Y') # Output : Y Feature

# 피쳐 생성

In [ ]:
train_x["new_1"] = train_x["X_01"] + train_x["X_02"] -train_x["X_03"]
test_x["new_1"] = test_x["X_01"] + test_x["X_02"] -test_x["X_03"]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [ ]:
train_x["new_2"] = np.sqrt(train_x["X_19"] * train_x["X_30"] /train_x["X_34"] )
test_x["new_2"] = np.sqrt(test_x["X_19"] * test_x["X_30"] /test_x["X_34"] )

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [ ]:
train_x["new_3"] = np.sqrt(train_x["X_20"] * train_x["X_31"] /train_x["X_35"] )
test_x["new_3"] = np.sqrt(test_x["X_20"] * test_x["X_31"] /test_x["X_35"] )

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [ ]:
train_x["new_4"] = np.sqrt(train_x["X_21"] * train_x["X_32"] /train_x["X_36"] )
test_x["new_4"] = np.sqrt(test_x["X_21"] * test_x["X_32"] /test_x["X_36"] )

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [ ]:
train_x["new_5"] = np.sqrt(train_x["X_22"] * train_x["X_33"] /train_x["X_37"] )
test_x["new_5"] = np.sqrt(test_x["X_22"] * test_x["X_33"] /test_x["X_37"] )

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [ ]:
train_x["new_6"] = np.log1p(train_x["X_44"] * train_x["X_43"] / train_x["X_42"] *  train_x["X_41"])
test_x["new_6"] = np.log1p(test_x["X_44"] * test_x["X_43"] / test_x["X_42"] *  test_x["X_41"])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [ ]:
train_x["new_7"] = (train_x["X_38"] *train_x["X_39"] + train_x["X_40"])
test_x["new_7"] = (test_x["X_38"] *test_x["X_39"] + test_x["X_40"])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [ ]:
train_x["new_16"] = (train_x["X_41"] *train_x["X_42"] + train_x["X_43"] + train_x["X_44"])/4
test_x["new_16"] = (test_x["X_41"] *test_x["X_42"] + test_x["X_43"] + test_x["X_44"])/4

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [ ]:
train_x["new_17"] = (train_x["X_01"] + train_x["X_02"]  + train_x["X_05"] + train_x["X_06"])
test_x["new_17"] = (test_x["X_01"] + test_x["X_02"]  + test_x["X_05"] + test_x["X_06"])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [ ]:
train_x["new_18"] =(train_x["X_07"] + train_x["X_08"] +train_x["X_09"]) *train_x["X_03"] 
test_x["new_18"] =(test_x["X_07"] + test_x["X_08"] +test_x["X_09"]) *test_x["X_03"] 

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [ ]:
train_x["new_19"] =(train_x["X_03"] +train_x["X_10"] + train_x["X_11"])
test_x["new_19"] =(test_x["X_03"] +test_x["X_10"] + test_x["X_11"])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [ ]:
train_x["new_20"] =train_x["X_07"] / train_x["X_03"]
test_x["new_20"] =test_x["X_07"] / test_x["X_03"]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [ ]:
train_x["new_21"] =train_x["X_08"] / (train_x["X_10"] + 0.00001)
test_x["new_21"] =test_x["X_08"] / (test_x["X_10"] + 0.00001)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [ ]:
train_x["new_22"] =train_x["X_09"] / (train_x["X_11"] + 0.00001)
test_x["new_22"] =test_x["X_09"] / (test_x["X_11"] + 0.00001)

In [ ]:
# 스크류 삽입 길이 - 스크류 삽입 길이
train_x["new_23"] =train_x["X_30"] - train_x["X_19"]
test_x["new_23"] =test_x["X_30"] - test_x["X_19"]

train_x["new_24"] =train_x["X_31"] - train_x["X_20"]
test_x["new_24"] =test_x["X_31"] - test_x["X_20"]

train_x["new_25"] =train_x["X_32"] - train_x["X_21"]
test_x["new_25"] =test_x["X_32"] - test_x["X_21"]

train_x["new_26"] =train_x["X_33"] - train_x["X_22"]
test_x["new_26"] =test_x["X_33"] - test_x["X_22"]


In [ ]:
# 커넥터 총 치수
train_x["new_27"] =train_x["X_24"] +train_x["X_25"] +train_x["X_26"] +\
                            train_x["X_27"] +train_x["X_28"] +train_x["X_29"] 

test_x["new_27"] =test_x["X_24"] +test_x["X_25"] +test_x["X_26"] +\
                           test_x["X_27"] +test_x["X_28"] +test_x["X_29"] 

In [ ]:
# 스크류 회전수 대비 삽입 깊이
train_x["new_29"] =train_x["X_31"] * train_x["X_35"]
test_x["new_29"] =test_x["X_31"] * test_x["X_35"]

train_x["new_31"] =train_x["X_33"] * train_x["X_37"]
test_x["new_31"] =test_x["X_33"] * test_x["X_37"]


In [ ]:
# 안테나 사이 최소 거리
train_x["new_32"] =abs(train_x["X_14"] - train_x["X_15"])
test_x["new_32"] =abs(test_x["X_14"] - test_x["X_15"])

train_x["new_33"] =abs(train_x["X_14"] - train_x["X_16"])
test_x["new_33"] =abs(test_x["X_14"] - test_x["X_16"])

train_x["new_34"] =abs(train_x["X_14"] - train_x["X_17"])
test_x["new_34"] =abs(test_x["X_14"] - test_x["X_17"])

train_x["new_35"] =abs(train_x["X_14"] - train_x["X_18"])
test_x["new_35"] =abs(test_x["X_14"] - test_x["X_18"])

train_x["new_36"] =abs(train_x["X_15"] - train_x["X_16"])
test_x["new_36"] =abs(test_x["X_15"] - test_x["X_16"])

train_x["new_37"] =abs(train_x["X_15"] - train_x["X_17"])
test_x["new_37"] =abs(test_x["X_15"] - test_x["X_17"])

train_x["new_38"] =abs(train_x["X_15"] - train_x["X_18"])
test_x["new_38"] =abs(test_x["X_15"] - test_x["X_18"])

train_x["new_39"] =abs(train_x["X_16"] - train_x["X_17"])
test_x["new_39"] =abs(test_x["X_16"] - test_x["X_17"])

train_x["new_40"] =abs(train_x["X_16"] - train_x["X_18"])
test_x["new_40"] =abs(test_x["X_16"] - test_x["X_18"])

train_x["new_41"] =abs(train_x["X_17"] - train_x["X_18"])
test_x["new_41"] =abs(test_x["X_17"] - test_x["X_18"])


In [ ]:
# 안테나 사이 최대 거리
train_x["new_42"] =train_x["X_14"] + train_x["X_15"]
test_x["new_42"] =test_x["X_14"] + test_x["X_15"]

train_x["new_43"] =train_x["X_14"] + train_x["X_16"]
test_x["new_43"] =test_x["X_14"] + test_x["X_16"]

train_x["new_44"] =train_x["X_14"] + train_x["X_17"]
test_x["new_44"] =test_x["X_14"] + test_x["X_17"]

train_x["new_45"] =train_x["X_14"] + train_x["X_18"]
test_x["new_45"] =test_x["X_14"] + test_x["X_18"]

train_x["new_46"] =train_x["X_15"] + train_x["X_16"]
test_x["new_46"] =test_x["X_15"] + test_x["X_16"]

train_x["new_47"] =train_x["X_15"] + train_x["X_17"]
test_x["new_47"] =test_x["X_15"] + test_x["X_17"]

train_x["new_48"] =train_x["X_15"] + train_x["X_18"]
test_x["new_48"] =test_x["X_15"] + test_x["X_18"]

train_x["new_49"] =train_x["X_16"] + train_x["X_17"]
test_x["new_49"] =test_x["X_16"] + test_x["X_17"]

train_x["new_50"] =train_x["X_16"] + train_x["X_18"]
test_x["new_50"] =test_x["X_16"] + test_x["X_18"]

train_x["new_51"] =train_x["X_17"] + train_x["X_18"]
test_x["new_51"] =test_x["X_17"] + test_x["X_18"]

In [ ]:
# 레이돔 부피
train_x["new_52"] =4/3 * train_x["X_41"]**3 *3.141592
test_x["new_52"] =4/3 * test_x["X_41"]**3 *3.141592

train_x["new_53"] =4/3 * train_x["X_42"]**3 *3.141592
test_x["new_53"] =4/3 * test_x["X_42"]**3 *3.141592

train_x["new_54"] =4/3 * train_x["X_43"]**3 *3.141592
test_x["new_54"] =4/3 * test_x["X_43"]**3 *3.141592

train_x["new_55"] =4/3 * train_x["X_44"]**3 *3.141592
test_x["new_55"] =4/3 * test_x["X_44"]**3 *3.141592


In [ ]:
# 스크류 삽입 길이 + 스크류 삽입 길이
train_x["new_56"] =train_x["X_30"] + train_x["X_19"]
test_x["new_56"] =test_x["X_30"] + test_x["X_19"]

train_x["new_57"] =train_x["X_31"] + train_x["X_20"]
test_x["new_57"] =test_x["X_31"] + test_x["X_20"]

train_x["new_58"] =train_x["X_32"] + train_x["X_21"]
test_x["new_58"] =test_x["X_32"] + test_x["X_21"]

train_x["new_59"] =train_x["X_33"] + train_x["X_22"]
test_x["new_59"] =test_x["X_33"] + test_x["X_22"]


In [ ]:
train_x.drop(['X_04','X_23','X_47','X_48','X_34','X_36'],1,inplace=True)
test_x.drop(['X_04','X_23','X_47','X_48','X_34','X_36'],1,inplace=True)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  after removing the cwd from sys.path.


#평가지표

In [ ]:
# 평가지표
from sklearn.metrics import mean_squared_error
def lg_nrmse(gt, preds):
    all_nrmse = []
    temp = len(gt.columns)
    gt = np.array(gt)
    preds = np.array(preds)
    for idx in range(temp): 
        rmse = mean_squared_error(gt[:,idx], preds[:,idx], squared=False)
        nrmse = rmse/np.mean(np.abs(gt[:,idx]))
        all_nrmse.append(nrmse)
    score = 1.2 * np.sum(all_nrmse[:8]) + 1.0 * np.sum(all_nrmse[8:14])
    print(score)
    return score


# k-fold - lgbm

In [ ]:
from sklearn.model_selection import KFold
import lightgbm 
kf = KFold(n_splits=10 , random_state = 42 , shuffle = True)
i = 1
lgbm_model_save = []
nrmse_score = []

for train_index, test_index in kf.split(train_x):
  
  print(train_index)
  X_train, X_test = train_x.iloc[train_index], train_x.iloc[test_index]
  Y_train, Y_test = train_y.iloc[train_index], train_y.iloc[test_index]

  lgbm_model= MultiOutputRegressor(lightgbm.LGBMRegressor(random_seed = 42,
                                                          num_leaves = 681, colsample_bytree = 0.7732774027764344, 
                                                          reg_alpha = 0.3718384437002339, reg_lambda = 5.467302098418594, 
                                                          max_depth = 15, learning_rate = 0.0037878535825736077, n_estimators= 2994, 
                                                          min_child_samples= 29, subsample= 0.5855365968947291)).fit(X_train, Y_train)

  lgbm_model_save.append(lgbm_model)
  temp = lg_nrmse(Y_test, pd.DataFrame(lgbm_model.predict(X_test)))
  nrmse_score.append(temp)
  print(f"{i}번째 폴드 끝")
  i += 1
print(sum(nrmse_score)/10)


[    0     1     2 ... 49506 49507 49508]
1.7730897060910544
1번째 폴드 끝
[    0     2     3 ... 49506 49507 49508]
1.7777500210173807
2번째 폴드 끝
[    1     2     3 ... 49506 49507 49508]
1.7772871238119012
3번째 폴드 끝
[    0     1     2 ... 49506 49507 49508]
1.8428351032340944
4번째 폴드 끝
[    0     1     2 ... 49505 49506 49508]
1.774895179640923
5번째 폴드 끝
[    0     1     2 ... 49504 49506 49507]
1.7938741199547696
6번째 폴드 끝
[    0     1     2 ... 49506 49507 49508]
1.8041502246994452
7번째 폴드 끝
[    0     1     2 ... 49506 49507 49508]
1.8048276726490087
8번째 폴드 끝
[    0     1     3 ... 49506 49507 49508]
1.7914831689700215
9번째 폴드 끝
[    0     1     2 ... 49505 49507 49508]
1.7624853495356565
10번째 폴드 끝
1.7902677669604254


In [ ]:
lgbm_result = pd.DataFrame(lgbm_model_save[0].predict(test_x)) +pd.DataFrame(lgbm_model_save[1].predict(test_x)) +\
pd.DataFrame(lgbm_model_save[2].predict(test_x)) +pd.DataFrame(lgbm_model_save[3].predict(test_x)) +\
pd.DataFrame(lgbm_model_save[4].predict(test_x)) +pd.DataFrame(lgbm_model_save[5].predict(test_x)) +\
pd.DataFrame(lgbm_model_save[6].predict(test_x)) +pd.DataFrame(lgbm_model_save[7].predict(test_x)) +\
pd.DataFrame(lgbm_model_save[8].predict(test_x)) +pd.DataFrame(lgbm_model_save[9].predict(test_x))

In [ ]:
lgbm_result = lgbm_result / 10

In [ ]:
lgbm_result.to_csv('/content/drive/MyDrive/last_optuna_lgbm2.csv', index=False)

# k-fold - catboost

In [ ]:
!pip install catboost

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 76.6 MB 1.1 MB/s 


In [ ]:
from sklearn.model_selection import KFold
import catboost
kf = KFold(n_splits=10 , random_state = 42 , shuffle = True)
i = 1
catboost_model_save = []
nrmse_score = []

for train_index, test_index in kf.split(train_x):
  
  print(train_index)
  X_train, X_test = train_x.iloc[train_index], train_x.iloc[test_index]
  Y_train, Y_test = train_y.iloc[train_index], train_y.iloc[test_index]

  catboost_model= MultiOutputRegressor(catboost.CatBoostRegressor(random_seed = 42,verbose=0)).fit(X_train, Y_train)

  catboost_model_save.append(catboost_model)
  temp = lg_nrmse(Y_test, pd.DataFrame(catboost_model.predict(X_test)))
  nrmse_score.append(temp)
  print(f"{i}번째 폴드 끝")
  i += 1
print(sum(nrmse_score)/10)

[    0     1     2 ... 49506 49507 49508]
1.8323416060079454
1번째 폴드 끝
[    0     2     3 ... 49506 49507 49508]
1.8306526625480661
2번째 폴드 끝
[    1     2     3 ... 49506 49507 49508]
1.8342655034072124
3번째 폴드 끝
[    0     1     2 ... 49506 49507 49508]
1.9050309135652383
4번째 폴드 끝
[    0     1     2 ... 49505 49506 49508]
1.8446210782233243
5번째 폴드 끝
[    0     1     2 ... 49504 49506 49507]
1.8565516214982163
6번째 폴드 끝
[    0     1     2 ... 49506 49507 49508]
1.867586515756977
7번째 폴드 끝
[    0     1     2 ... 49506 49507 49508]
1.862420820434746
8번째 폴드 끝
[    0     1     3 ... 49506 49507 49508]
1.8521666582431513
9번째 폴드 끝
[    0     1     2 ... 49505 49507 49508]
1.8299559680450201
10번째 폴드 끝
1.8515593347729897


In [ ]:
catboost_result = pd.DataFrame(catboost_model_save[0].predict(test_x)) +pd.DataFrame(catboost_model_save[1].predict(test_x)) +\
pd.DataFrame(catboost_model_save[2].predict(test_x)) +pd.DataFrame(catboost_model_save[3].predict(test_x)) +\
pd.DataFrame(catboost_model_save[4].predict(test_x)) +pd.DataFrame(catboost_model_save[5].predict(test_x)) +\
pd.DataFrame(catboost_model_save[6].predict(test_x)) +pd.DataFrame(catboost_model_save[7].predict(test_x)) +\
pd.DataFrame(catboost_model_save[8].predict(test_x)) +pd.DataFrame(catboost_model_save[9].predict(test_x))

In [ ]:
catboost_result = catboost_result / 10

In [ ]:
catboost_result.to_csv('./last_default_catboost.csv', index=False)

#k-fold -et

In [15]:
from sklearn.model_selection import KFold
from sklearn.ensemble import ExtraTreesRegressor
kf = KFold(n_splits=3 , random_state = 42 , shuffle = True)
i = 1
et_model_save = []
nrmse_score = []

for train_index, test_index in kf.split(train_x):
  
  print(train_index)
  X_train, X_test = train_x.iloc[train_index], train_x.iloc[test_index]
  Y_train, Y_test = train_y.iloc[train_index], train_y.iloc[test_index]

  et_model= MultiOutputRegressor(ExtraTreesRegressor(random_state=42,n_estimators = 310, max_depth = 18,
                                                     min_samples_split = 17, min_samples_leaf = 2)).fit(X_train, Y_train)

  et_model_save.append(et_model)
  temp = lg_nrmse(Y_test, pd.DataFrame(et_model.predict(X_test)))
  nrmse_score.append(temp)
  print(f"{i}번째 폴드 끝")
  i += 1
print(sum(nrmse_score)/10)

[    2     3     5 ... 49506 49507 49508]


NameError: ignored

In [ ]:
et_result = pd.DataFrame(et_model_save[0].predict(test_x)) + pd.DataFrame(et_model_save[1].predict(test_x)) + pd.DataFrame(et_model_save[2].predict(test_x))
et_result = et_result / 3

In [ ]:
et_result.to_csv('./last_et.csv', index=False)

In [ ]:
result = (lgbm_result * 0.5 +  + catboost_result * 0.4 + et_result * 0.1) 

## Submit

In [ ]:
submit = pd.read_csv('/content/drive/MyDrive/[데이콘]LG/data/sample_submission.csv')

In [ ]:
for idx, col in enumerate(submit.columns):
    if col=='ID':
        continue
    submit[col] =result.reset_index().iloc[:,idx]
print('Done.')

Done.


In [ ]:
submit.to_csv('./last3.csv', index=False)

In [ ]:
submit

ID      Y_01      Y_02      Y_03       Y_04       Y_05  \
0      TEST_00001  1.515097  1.312985  1.198807  14.104733  31.404605   
1      TEST_00002  1.511303  1.282531  1.179547  13.113096  31.166875   
2      TEST_00003  1.525708  1.176557  1.133524  14.708948  32.420346   
3      TEST_00004  1.438650  1.171226  1.036586  14.711755  32.052778   
4      TEST_00005  1.367803  1.011124  0.973744  14.762581  31.318976   
...           ...       ...       ...       ...        ...        ...   
39603  TEST_39604  1.303817  0.991499  1.037843  12.653399  30.720536   
39604  TEST_39605  1.224456  0.849391  0.927178  14.166659  31.192019   
39605  TEST_39606  1.242181  0.913053  0.965991  13.106020  30.862033   
39606  TEST_39607  1.209638  0.828047  0.906591  13.886667  31.371863   
39607  TEST_39608  1.287888  0.899167  0.977222  12.683991  30.460145   

            Y_06      Y_07       Y_08       Y_09       Y_10       Y_11  \
0      16.822525  3.144819 -25.970132 -26.027481 -22.036523  24.647176   
1      16.532901  3.195854 -26.138729 -26.155720 -22.341600  24.319377   
2      16.710202  3.048599 -25.890888 -25.932797 -22.020298  24.658355   
3      17.170349  3.080339 -25.613493 -25.624437 -21.753447  24.974740   
4      16.865518  3.162350 -25.743946 -25.780334 -22.115972  24.677612   
...          ...       ...        ...        ...        ...        ...   
39603  16.708370  3.212313 -26.469242 -26.449145 -22.960212  24.342704   
39604  16.865317  3.208931 -26.369103 -26.384039 -22.808478  24.487003   
39605  16.645131  3.233810 -26.531984 -26.543712 -22.983240  24.234476   
39606  16.846740  3.162461 -26.359608 -26.366348 -22.770420  24.554186   
39607  16.571889  3.254494 -26.662450 -26.614024 -22.999851  24.034160   

            Y_12       Y_13       Y_14  
0     -25.926354 -25.899284 -25.957124  
1     -26.085885 -26.092108 -26.086921  
2     -25.857513 -25.881054 -25.857326  
3     -25.582061 -25.572164 -25.589099  
4     -25.679204 -25.723076 -25.700010  
...          ...        ...        ...  
39603 -26.417378 -26.376373 -26.392246  
39604 -26.292339 -26.307525 -26.336411  
39605 -26.476997 -26.451907 -26.512576  
39606 -26.337252 -26.307699 -26.373538  
39607 -26.584361 -26.567702 -26.578472  

[39608 rows x 15 columns]